### ISSUE TITLE
Issue Running Kha Benchmark

### ISSUE THREAD

**Issue by jakeklassen** [dmitryhryppa/Frameworks_test#3]
First of all, awesome work.

I am new to Haxe so hopefully this isn't something obvious, but when running `haxelib run kha` on windows 10 in the Kha folder I get the following error:

```
Haxe stderr: ..\Sources/Empty.hx:12: characters 7-27 : Type not found : kha.math.FastMatrix3
..\Sources/Main.hx:5: lines 5-10 : Defined in this class
```

Do I need to run anything else? Maybe some quick setup instructions (if needed) in the README per framework could help for newbies like myself coming to asses frameworks.

Thanks

**Comment by larsiusprime** [comment]
Yes, this would be great, a set of instructions for running each of the demos (and installing any required dependencies). 

Perhaps @robdangerous could add this as PR for kha.

**Comment by RobDangerous** [comment]
You need the git version of Kha to run the benchmarks. It's all cutting edge here.
Will send a PR with Kha instructions.

**Comment by jakeklassen** [comment]
Thanks guys. I am getting a different error after the switch to git, but I will resolve it in the appropriate repo.

```
Error parsing haxelib.json for kha@dev: [file_contents,C:\HaxeToolkit\haxe\lib\kha/git/haxelib.json]
```
